[[redirects]]
  from = "/api*"
  to = "https://api.weather.yandex.ru/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Yandex-API-Key = "d0f8a1fc-f9f3-48d6-84b0-aa31d9f7d8b6"
